# Site settings
title: modelx
email: fumito.ham@gmail.com
description: >
  Python-spreadsheets hybrid
lang: en-US

baseurl: "/modelx-site" # the subpath of your site, e.g. /blog/
url: "https://fumitoh.github.io" # the base hostname & protocol for your site
git_address: https://github.com/fumitoh/modelx
# git_edit_address: https://github.com/aksakalli/jekyll-doc-theme/blob/gh-pages
twitter_username: fumitoham
github_username: fumitoh

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: cosmo

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md

defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true

google_analytics: UA-108824439-4
